<a href="https://colab.research.google.com/github/TurboNeso/Testrepo/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd

In [3]:
x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}
df = pd.DataFrame(x)

In [4]:
df.head()

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [5]:
df

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [6]:
x = df['ID']
x

0    1
1    2
2    3
3    4
Name: ID, dtype: int64

In [7]:
type(x)

pandas.core.series.Series

In [8]:
z = df[['Name','Salary']]
z

Name  Salary
0  Rose  100000
1  John   80000
2  Jane   50000
3  Mary   60000

In [9]:
y = {'Student': ['David', 'Samuel', 'Terry', 'Evan'], 
     'Age':[27, 24, 22, 32], 
     'Country': ['UK', 'Canada', 'China', 'USA'], 
     'Course': ['Python', 'Data Structure', 'Machine Learning', 'Web devolepment'], 
     'Marks': [85,72, 89, 76]}

df = pd.DataFrame(y)
df

Student  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada    Data Structure     72
2   Terry   22   China  Machine Learning     89
3    Evan   32     USA   Web devolepment     76

In [10]:
z = df[['Student', 'Age']]
z

Student  Age
0   David   27
1  Samuel   24
2   Terry   22
3    Evan   32

In [11]:
df.loc[1]

Student            Samuel
Age                    24
Country            Canada
Course     Data Structure
Marks                  72
Name: 1, dtype: object

In [12]:
df.iloc[2, 3]

'Machine Learning'

In [13]:
df.loc[0, 'Marks']

85

In [14]:
df2 = df
df2 = df2.set_index('Student')

In [15]:
df2.head()

Age Country            Course  Marks
Student                                      
David     27      UK            Python     85
Samuel    24  Canada    Data Structure     72
Terry     22   China  Machine Learning     89
Evan      32     USA   Web devolepment     76

In [16]:
df2.loc["Samuel", "Country"]

'Canada'

In [17]:
df2.iloc[2:4, 3]

Student
Terry    89
Evan     76
Name: Marks, dtype: int64

In [18]:
df.loc[2:4, "Age":"Marks"]

Age Country            Course  Marks
2   22   China  Machine Learning     89
3   32     USA   Web devolepment     76

**Numpy cheatsheet**

In [19]:
#create pyton list
a = ['0', 1, 'two', '3', 4]

In [20]:
a[0]

'0'

In [21]:
print(a[0])

0


**What is Numpy?**

NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices.A numpy array is similar to a list. NumPy stands for Numerical Python and it is an open source project.The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing **numpy**:

In [22]:
#Import the library
import numpy as np

In [23]:
a = [0, 1, 2, 3, 4]
b = np.array(a)
b

array([0, 1, 2, 3, 4])

In [24]:
print(b[0])

0


In [25]:
print(np.__version__)

1.21.6


In [26]:
type(b)

numpy.ndarray

In [27]:
b.dtype

dtype('int64')

In [28]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here
type(b)
b.dtype



dtype('float64')

In [29]:
c = np.array([0, 1, 2, 3, 4])
c

array([0, 1, 2, 3, 4])

In [30]:
# Assign the first element to 100
c[0]= 100
c

array([100,   1,   2,   3,   4])

In [31]:
# Assign the 5th element to 0
c[4] = 0
c

array([100,   1,   2,   3,   0])

**Try it yourself** 

Assign the value 20 for the second element in the given array.

In [33]:
a = np.array([10, 2, 30, 40,50])

a[1] = 20

In [34]:
a

array([10, 20, 30, 40, 50])

**Slicing** 


Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].The element at end index is not being included in the output.

We can select the elements from 1 to 3 and assign it to a new numpy array d as follows:

In [35]:
c[1:4]

array([1, 2, 3])

In [36]:
c[3:5] = 250, 345
c

array([100,   1,   2, 250, 345])

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [38]:
print(arr[:4])

[1 2 3 4]


In [39]:
print(arr[1:5:])

[2 3 4 5]


In [40]:
print(arr[4:])

[5 6 7]


In [41]:
select = [0, 2 , 3, 4]
select

[0, 2, 3, 4]

In [42]:
d = c[select]
d

array([100,   2, 250, 345])

In [43]:
c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

In [44]:
a.size

5

In [45]:
a.ndim

1

In [46]:
a.shape

(5,)

In [47]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

b.ndim

1

In [48]:
b.shape


(7,)

In [49]:
b.size

7

In [50]:
mean = b.mean()
mean


40.0

In [51]:
STD = b.std()
STD

20.0